version: '3.8'
services:
  mongo-express:
    image: mongo-express
    container_name: sprechi-mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGODB_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGODB_PASSWORD
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@db:27017/
    restart: unless-stopped
    #ports:
    #  - 8081:8081
    networks:
      - default
      - proxy
    #depends_on:
    #  db:
    #    condition: service_healthy
  sprechi:
    env_file:
      - stack.env # works with portainer      
networks:
  proxy:
    external: true